name: .NET Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ai-lander.sln

      - name: Build solution
        run: dotnet build ai-lander.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test ai-lander.sln --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage"

      - name: Upload code coverage report
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: '**/TestResults/*/coverage.cobertura.xml'
